"""Formation profile — per-(team, phase) feature vector for strengths/weaknesses scoring.

Two profile types coexist because no ingested match has both events and tracking yet:

- **Tracking profile**: per-(team, phase) compactness vector built from ``shape_time_series``
  and the phase classifier output. Captures team shape under different game states.
- **Events profile**: per-team aggregate (xT generated/conceded, PPDA, field tilt, shots,
  goals). No phase split because we don't have an events-only phase classifier yet.

Both feed the same baseline + z-score machinery in ``strengths.py``. When a unified
events+tracking match (e.g. PFF FC) is ingested later, the two profiles can be merged
into a single multi-axis profile per ``docs/architecture/analytics-layer.md``.
"""

from __future__ import annotations

from dataclasses import dataclass

import pandas as pd

from football_analysis.analytics.formations.shape import shape_time_series
from football_analysis.analytics.team.field_tilt import compute_field_tilt
from football_analysis.analytics.team.ppda import compute_ppda

# Cap PPDA when the opponent makes zero defensive actions (compute_ppda returns inf).
# 50 is far above any realistic value (>30 is "no press"), keeps z-scores well-defined.
PPDA_INF_CAP: float = 50.0

# Minimum frames per phase before we trust the per-phase tracking profile.
MIN_FRAMES_PER_PHASE: int = 25  # ~1 s at 25 Hz


@dataclass(frozen=True)
class FormationProfile:
    """Feature vector for one (team, phase, sample-source) slice."""

    team_id: str
    phase: str | None  # None for events-side profile (no phase axis)
    sample: str  # 'tracking' or 'events'
    metrics: dict[str, float]
    n_frames: int  # how many frames or events backed this profile (signal weight)


def extract_tracking_profile(
    tracking: pd.DataFrame,
    classified: pd.DataFrame,
    team_id: str,
    attacking_right: bool = True,
    min_frames_per_phase: int = MIN_FRAMES_PER_PHASE,
) -> dict[str, FormationProfile]:
    """Build one ``FormationProfile`` per phase for ``team_id``.

    Args:
        tracking: canonical long-form tracking DataFrame.
        classified: output of ``classify_frames`` (must have ``frame_id`` + ``phase``).
        team_id: team to profile.
        attacking_right: whether this team is attacking +x in canonical coords.
        min_frames_per_phase: skip phases with fewer frames than this (low-signal).

    Returns:
        ``{phase: FormationProfile}``. Phases with insufficient samples are absent.
    """
    shape_ts = shape_time_series(tracking, team_id=team_id, attacking_right=attacking_right)
    if shape_ts.empty:
        return {}
    merged = shape_ts.merge(classified[["frame_id", "phase"]], on="frame_id", how="inner")
    if merged.empty:
        return {}

    out: dict[str, FormationProfile] = {}
    for phase_label, sub in merged.groupby("phase"):
        if len(sub) < min_frames_per_phase:
            continue
        metrics = {
            "length_mean": float(sub["length"].mean()),
            "width_mean": float(sub["width"].mean()),
            "hull_area_mean": float(sub["convex_hull_area"].mean()),
            "def_line_mean": float(sub["defensive_line_height"].mean()),
            "off_line_mean": float(sub["offensive_line_height"].mean()),
            "vertical_compactness_mean": float(sub["vertical_compactness"].mean()),
        }
        out[str(phase_label)] = FormationProfile(
            team_id=team_id,
            phase=str(phase_label),
            sample="tracking",
            metrics=metrics,
            n_frames=len(sub),
        )
    return out


def extract_events_profile(
    enriched_events: pd.DataFrame,
    team_id: str,
    opponent_id: str,
) -> FormationProfile:
    """Per-team events-side profile.

    ``enriched_events`` must already carry the ``xt_delta`` column (e.g. via
    ``analytics.pipeline.runner.run`` or ``analytics.possession_value.xt.apply_xt``).
    """
    team_events = enriched_events[enriched_events["team_id"] == team_id]
    opp_events = enriched_events[enriched_events["team_id"] == opponent_id]

    if "xt_delta" not in enriched_events.columns:
        raise ValueError("enriched_events must include 'xt_delta' column (run apply_xt first)")

    xt_generated = float(team_events["xt_delta"].clip(lower=0).sum(skipna=True))
    # 'xt_conceded' = xT generated by the opponent against us
    xt_conceded = float(opp_events["xt_delta"].clip(lower=0).sum(skipna=True))

    raw_ppda = compute_ppda(enriched_events, team_id, opponent_id)
    ppda = PPDA_INF_CAP if raw_ppda == float("inf") else float(raw_ppda)
    tilt = float(compute_field_tilt(enriched_events, team_id, opponent_id))

    shots = team_events[team_events["action_type"] == "shot"]
    n_shots = float(len(shots))
    n_goals = float(len(shots[shots["result"] == "success"]))

    metrics = {
        "xt_generated": xt_generated,
        "xt_conceded": xt_conceded,
        "ppda": ppda,
        "field_tilt": tilt,
        "shots": n_shots,
        "goals": n_goals,
    }
    return FormationProfile(
        team_id=team_id,
        phase=None,
        sample="events",
        metrics=metrics,
        n_frames=len(team_events),
    )
